// Read-only IL evidence inventory; records constants, method calls and hashes, not decompiled implementations.
using System.Reflection;using System.Reflection.Emit;using System.Runtime.Loader;using System.Security.Cryptography;using System.Text.Json;
var path=Path.GetFullPath(args[0]);var dir=Path.GetDirectoryName(path)!;AssemblyLoadContext.Default.Resolving+=(c,n)=>{var p=Path.Combine(dir,n.Name+".dll");return File.Exists(p)?c.LoadFromAssemblyPath(p):null;};var asm=AssemblyLoadContext.Default.LoadFromAssemblyPath(path);
var ops=typeof(OpCodes).GetFields(BindingFlags.Static|BindingFlags.Public).Where(f=>f.FieldType==typeof(OpCode)).Select(f=>(OpCode)f.GetValue(null)!).ToDictionary(o=>unchecked((ushort)o.Value));
var records=new List<object>();
foreach(var type in asm.GetTypes())foreach(var method in type.GetMethods(BindingFlags.DeclaredOnly|BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance).Cast<MethodBase>().Concat(type.GetConstructors(BindingFlags.DeclaredOnly|BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance))){
 var il=method.GetMethodBody()?.GetILAsByteArray();if(il==null)continue;var constants=new List<object>();var calls=new List<object>();var i=0;
 while(i<il.Length){var offset=i;ushort c=il[i++];if(c==0xfe)c=(ushort)(0xfe00|il[i++]);var op=ops[c];int n=op.OperandType switch{OperandType.InlineNone=>0,OperandType.ShortInlineI or OperandType.ShortInlineVar or OperandType.ShortInlineBrTarget=>1,OperandType.InlineVar=>2,OperandType.InlineI8 or OperandType.InlineR=>8,OperandType.InlineSwitch=>4+4*BitConverter.ToInt32(il,i),_=>4};object? value=null;
 if(op.Name!.StartsWith("ldc.i4.")){var tail=op.Name.Substring(7);value=tail=="s"?(sbyte)il[i]:tail=="m1"?-1:int.Parse(tail);}else if(op.Name=="ldc.i4")value=BitConverter.ToInt32(il,i);else if(op.Name=="ldc.i8")value=BitConverter.ToInt64(il,i);else if(op.Name=="ldc.r4")value=BitConverter.ToSingle(il,i);else if(op.Name=="ldc.r8")value=BitConverter.ToDouble(il,i);else if(op.Name=="ldstr")try{value=asm.ManifestModule.ResolveString(BitConverter.ToInt32(il,i));}catch{}
 if(value!=null)constants.Add(new{offset,op=op.Name,value});
 if(op.OperandType==OperandType.InlineMethod){var token=BitConverter.ToInt32(il,i);string? target=null;try{var m=asm.ManifestModule.ResolveMethod(token);target=m?.DeclaringType?.FullName+"."+m?.Name;}catch{target="unresolved-token:"+token;}calls.Add(new{offset,token,target});}i+=n;
 }
 records.Add(new{type=type.FullName,method=method.Name,signature=method.ToString(),metadataToken=method.MetadataToken,ilBytes=il.Length,ilSha256=Convert.ToHexString(SHA256.HashData(il)).ToLowerInvariant(),constants,calls});
}
Console.WriteLine(JsonSerializer.Serialize(new{assembly=path,sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant(),literalFields=asm.GetTypes().SelectMany(t=>t.GetFields(BindingFlags.DeclaredOnly|BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.Instance).Where(f=>f.IsLiteral).Select(f=>new{type=t.FullName,name=f.Name,token=f.MetadataToken,value=f.GetRawConstantValue()})),enums=asm.GetTypes().Where(t=>t.IsEnum).Select(t=>new{name=t.FullName,values=Enum.GetValues(t).Cast<object>().Select(v=>new{name=v.ToString(),value=Convert.ToInt32(v)})}),records},new JsonSerializerOptions { NumberHandling=System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals }));
