import {browserExecutable} from './browser-executable.mjs';
import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const b=await chromium.launch({headless:true,executablePath:browserExecutable}),p=await b.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});const errors=[],checks=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const state=async()=>JSON.parse(await p.evaluate(()=>window.render_game_to_text()));const snap=async n=>{await p.waitForTimeout(220);await p.screenshot({path:`artifacts/qa/flow-${n}.png`});};const check=async n=>{checks.push({name:n,state:await state()});console.log('PASS',n);};const click=async id=>{await p.locator('#'+id).click();await p.waitForTimeout(80);};
async function drag(id,x,y){const a=await p.locator('#'+id).boundingBox();assert.ok(a,id);await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(x,y,{steps:18});await p.mouse.up();await p.waitForTimeout(80);}
try{
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:5175');await p.waitForFunction(()=>document.documentElement.dataset.sceneReady==='true');await snap('menu');
 await p.mouse.click(902,917);assert.equal((await state()).mode,'shop');assert.equal((await state()).cash,258);assert.equal((await state()).estimate,118);await check('visible Load Game starts actual day 6');await snap('loaded');
 await p.mouse.move(955,974);await p.waitForTimeout(100);await click('tool-material');await p.mouse.move(950,830);await p.waitForTimeout(100);assert.equal((await state()).book,'material');assert.equal((await state()).estimate,118);await check('tool follows pointer and opens original material page');await snap('material');
 await drag('book-canvas',220,568);assert.equal((await state()).estimate,118);assert.ok((await state()).tags.some(t=>t.id==='canvas'));await check('real drag adds canvas without silently removing claimed brand');
 await click('book-brands');await click('book-next');await drag('book-wrong-material',220,483);assert.equal((await state()).estimate,55);assert.equal((await state()).tags.some(t=>t.id==='brand-easy-enough'),false);await check('wrong material challenge removes original brand value');await snap('appraisal55');
 await click('book-close');await click('calculator-toggle');await snap('calculator');await click('key-4');await click('key-5');assert.equal((await state()).quote,'45');await click('offer');assert.equal((await state()).cash,213);assert.equal((await state()).result,'bought');assert.equal((await state()).stock.length,7);await check('native calculator settles 45 with one owned backpack');await snap('bought');
 await click('next-visitor');assert.equal((await state()).mode,'sales');await snap('sales');await click('sales-customer');await click('offer');assert.equal((await state()).cash,508);assert.equal((await state()).result,'sold');await check('first recorded resale adds 295');
 await click('next-visitor');assert.equal((await state()).visit,'day6-combat-boots');await click('calculator-toggle');await click('key-1');await click('key-5');await click('key-0');await click('offer');assert.equal((await state()).cash,358);await check('next NPC and item load and settle independently');
 await click('next-visitor');await click('sales-customer');await click('offer');assert.equal((await state()).cash,428);await click('next-visitor');assert.equal((await state()).phase,'narrative');await click('npc-dialogue');await snap('story');
 for(let i=0;i<8;i++){if((await state()).phase==='between')break;const d=p.locator('#dialogue-next');if(await d.count())await d.click();else if(await p.locator('#npc-dialogue').count())await click('npc-dialogue');await p.waitForTimeout(80);}
 assert.equal((await state()).phase,'between');await click('night-leave');await snap('street-night');await p.keyboard.press('e');await p.waitForTimeout(100);assert.equal((await state()).mode,'summary');await snap('summary');await check('story dialogue leads to actual day summary');
 await click('aux-sleep');assert.equal((await state()).day,7);assert.equal((await state()).mode,'street');await snap('street');await p.keyboard.down('ArrowLeft');await p.waitForTimeout(1420);await p.keyboard.up('ArrowLeft');await p.keyboard.press('e');await p.waitForTimeout(100);assert.equal((await state()).mode,'flower');await click('aux-horong');const before=(await state()).cash;await click('aux-horong-buy');assert.equal((await state()).cash,before-50);assert.equal((await state()).plantDays,3);await snap('flowers');await check('street doors and 50U flower transaction operate');
 assert.deepEqual(errors,[]);await fs.writeFile('artifacts/qa/flow-report.json',JSON.stringify({passed:true,checks,errors},null,2));
}catch(e){await snap('failure');await fs.writeFile('artifacts/qa/flow-report.json',JSON.stringify({passed:false,error:String(e),checks,errors,state:await state()},null,2));throw e;}finally{await b.close();}
