/** Official 1.0.5 Demo facts; source day/item identity only, never inferred from a face. */
export type DemoPersonality = 'wishy-washy' | 'active' | 'cautious' | 'emotional' | 'fixie';
export type DemoScriptHook = 'D06BrandAfter' | 'D07Choi' | 'D08ArtHue' | 'D08ArtAfter' | 'D08Yeongi' | 'D11PrivateAfter' | 'UnWilling';
export interface DemoCustomerFacts {
  visitId: string;
  status: 'matched-script' | 'unknown' | 'not-applicable';
  eventId: string | null;
  itemDefinitionId: string | null;
  characterId: string | null;
  personality: DemoPersonality | null;
  /** Initial NewPriceStamp is the NPC estimate, not a CustomerSuggestPrice event. */
  initialAskingPrice: number | null;
  openingAskStatus: 'not-established';
  initialModifier: 'none-at-haggle-construction' | 'unknown';
  scriptHookId: DemoScriptHook | null;
  /** Script hooks suppress normal personality idle pipes during construction. */
  normalIdleTimers: boolean | null;
  /** Native card IDs forming the customer's belief, not actual item cards. */
  defaultAssumptionIds: string[];
  source: { archiveSha256: string; applicationVersion: string; asset: string; storeEventPathId: number; itemPathId: number; characterPathId: number } | null;
  reason: string;
}
export const DEMO_CUSTOMER_FACTS: Readonly<Record<string, DemoCustomerFacts>> = {
  "day6-backpack-soldier": {
    "visitId": "day6-backpack-soldier",
    "status": "matched-script",
    "eventId": "D06_brand_after",
    "itemDefinitionId": "EE_02",
    "characterId": "random_female_1020",
    "personality": "active",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": "D06BrandAfter",
    "normalIdleTimers": false,
    "defaultAssumptionIds": [
      "gray_backpack",
      "blue_slightdmg",
      "green_easyenough"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24215,
      "itemPathId": 24586,
      "characterPathId": 23851
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day6-strong-leg": {
    "visitId": "day6-strong-leg",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "chippieLeg",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day6-combat-boots": {
    "visitId": "day6-combat-boots",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "EE_shoes",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day6-early-poster": {
    "visitId": "day6-early-poster",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "poster_09",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day6-darcy-task": {
    "visitId": "day6-darcy-task",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day7-fixie-bag": {
    "visitId": "day7-fixie-bag",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "FF_07",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day7-research-poster": {
    "visitId": "day7-research-poster",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "Poster_01",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day7-backpack-resale": {
    "visitId": "day7-backpack-resale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "EE_02",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day7-crabgrass": {
    "visitId": "day7-crabgrass",
    "status": "matched-script",
    "eventId": "D07_choi",
    "itemDefinitionId": "plantPot",
    "characterId": "profchoi",
    "personality": "wishy-washy",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": "D07Choi",
    "normalIdleTimers": false,
    "defaultAssumptionIds": [
      "gray_plant",
      "green_clay",
      "blue_slightdmg"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24127,
      "itemPathId": 24783,
      "characterPathId": 23850
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day7-flawless-bag-resale": {
    "visitId": "day7-flawless-bag-resale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "No_03_copy",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day7-bookmark": {
    "visitId": "day7-bookmark",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "bookmark",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day7-avac-secretary": {
    "visitId": "day7-avac-secretary",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day7-boots-refused-sale": {
    "visitId": "day7-boots-refused-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "EE_shoes",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day7-golden-glasses": {
    "visitId": "day7-golden-glasses",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "glasses_02",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day7-finer-warning": {
    "visitId": "day7-finer-warning",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day7-paperbag-sale": {
    "visitId": "day7-paperbag-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "AA_02_01_t",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-gioconda": {
    "visitId": "day8-gioconda",
    "status": "matched-script",
    "eventId": "D08_art_hue",
    "itemDefinitionId": "monalisa",
    "characterId": "random_female_5060",
    "personality": "active",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": "D08ArtHue",
    "normalIdleTimers": false,
    "defaultAssumptionIds": [
      "gray_2dArt",
      "green_canvas",
      "blue_slightdmg"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24198,
      "itemPathId": 24764,
      "characterPathId": 23853
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day8-fixie-bag-sale": {
    "visitId": "day8-fixie-bag-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "FF_07",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-avac-card": {
    "visitId": "day8-avac-card",
    "status": "matched-script",
    "eventId": "D08_avacCard",
    "itemDefinitionId": "AVACcard_01",
    "characterId": "random_female_1020",
    "personality": "active",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": null,
    "normalIdleTimers": true,
    "defaultAssumptionIds": [
      "gray_idcard",
      "blue_slightdmg",
      "green_plastic"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24128,
      "itemPathId": 24518,
      "characterPathId": 23851
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day8-taxidermied-butterfly-sale": {
    "visitId": "day8-taxidermied-butterfly-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "butterfly",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-golden-glasses-sale": {
    "visitId": "day8-golden-glasses-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "glasses_02",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-doll": {
    "visitId": "day8-doll",
    "status": "matched-script",
    "eventId": "D08_yeongi",
    "itemDefinitionId": "YGdoll",
    "characterId": "yeongi",
    "personality": "active",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": "D08Yeongi",
    "normalIdleTimers": false,
    "defaultAssumptionIds": [
      "gray_doll",
      "blue_slightdmg",
      "blue_artist",
      "green_velvet",
      "blue_pop"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24130,
      "itemPathId": 24716,
      "characterPathId": 23862
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day8-rabbit": {
    "visitId": "day8-rabbit",
    "status": "matched-script",
    "eventId": "D08_art_after",
    "itemDefinitionId": "StandingRabbit",
    "characterId": "random_male_3040",
    "personality": "wishy-washy",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": "D08ArtAfter",
    "normalIdleTimers": false,
    "defaultAssumptionIds": [
      "gray_3dArt",
      "blue_artist",
      "blue_slightdmg",
      "green_wood"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24216,
      "itemPathId": 24699,
      "characterPathId": 23855
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day8-crocodile": {
    "visitId": "day8-crocodile",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "happyCrocTears",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-picked-hoverboard-sale": {
    "visitId": "day8-picked-hoverboard-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "VT_2068_t",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-my-mom": {
    "visitId": "day8-my-mom",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "girlWithRibbon",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-vermeer-acquired": {
    "visitId": "day8-vermeer-acquired",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": "girlWithEarrings",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day8-doll-declined-sale": {
    "visitId": "day8-doll-declined-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "YGdoll",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-fantastic-hoverboard": {
    "visitId": "day8-fantastic-hoverboard",
    "status": "matched-script",
    "eventId": "D08_unwillingHusband",
    "itemDefinitionId": "VT_2073_solHan",
    "characterId": "random_male_5060",
    "personality": "wishy-washy",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": "UnWilling",
    "normalIdleTimers": false,
    "defaultAssumptionIds": [
      "gray_hoverboard",
      "green_vertivo",
      "green_vertivo_vtvsteel",
      "blue_perfect",
      "blue_pop"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24221,
      "itemPathId": 24712,
      "characterPathId": 23856
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day8-avac-card-sale": {
    "visitId": "day8-avac-card-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "AVACcard",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-vermeer-sale": {
    "visitId": "day8-vermeer-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "girlWithEarrings",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day8-plain-sunglasses-sale": {
    "visitId": "day8-plain-sunglasses-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "sunglasses_01",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-boots-declined-sale": {
    "visitId": "day9-boots-declined-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "EE_shoes",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-black-umbrella-sale": {
    "visitId": "day9-black-umbrella-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "umbrella_05_04",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-umbrella-side-deal": {
    "visitId": "day9-umbrella-side-deal",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-doll-sale": {
    "visitId": "day9-doll-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "YGdoll",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-time-device": {
    "visitId": "day9-time-device",
    "status": "matched-script",
    "eventId": "D09_timeCinema",
    "itemDefinitionId": "tCinema",
    "characterId": "random_female_3040",
    "personality": "active",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": null,
    "normalIdleTimers": true,
    "defaultAssumptionIds": [
      "gray_machine",
      "blue_fairlydmg",
      "green_plastic"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24131,
      "itemPathId": 24799,
      "characterPathId": 23852
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day9-my-mom-declined-sale": {
    "visitId": "day9-my-mom-declined-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "girlWithRibbon",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-officer-visit": {
    "visitId": "day9-officer-visit",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day9-seoul-stamp": {
    "visitId": "day9-seoul-stamp",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "Stamp_02",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-chippie-sculpture-sale": {
    "visitId": "day9-chippie-sculpture-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "hwangArt_01",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day9-bookmark-sale": {
    "visitId": "day9-bookmark-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "bookmark",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day10-fine-visit": {
    "visitId": "day10-fine-visit",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day10-crocodile-sale": {
    "visitId": "day10-crocodile-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "happyCrocTears",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day10-time-device-sale": {
    "visitId": "day10-time-device-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "tCinema",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day10-stabilizer-warning": {
    "visitId": "day10-stabilizer-warning",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day10-sweet-pocket-sale": {
    "visitId": "day10-sweet-pocket-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "poFriend",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day11-reporting-setup": {
    "visitId": "day11-reporting-setup",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day11-private-slot-tutorial": {
    "visitId": "day11-private-slot-tutorial",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  },
  "day11-meaningful-paper": {
    "visitId": "day11-meaningful-paper",
    "status": "matched-script",
    "eventId": "D11_private_after",
    "itemDefinitionId": "presidentSpeech",
    "characterId": "privateAfter",
    "personality": "wishy-washy",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": "D11PrivateAfter",
    "normalIdleTimers": false,
    "defaultAssumptionIds": [
      "gray_sheet",
      "green_paper",
      "blue_fairlydmg"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24218,
      "itemPathId": 24792,
      "characterPathId": 23849
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day11-rabbit-sale": {
    "visitId": "day11-rabbit-sale",
    "status": "unknown",
    "eventId": null,
    "itemDefinitionId": "StandingRabbit",
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "No unique same-day purchase StoreEvent and exact Item pointer. Do not infer a buyer from an earlier seller of the same item."
  },
  "day11-hoverboard-display": {
    "visitId": "day11-hoverboard-display",
    "status": "matched-script",
    "eventId": "D11_preAvarice101",
    "itemDefinitionId": "FZ_2076",
    "characterId": "preAvarice1",
    "personality": "active",
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "none-at-haggle-construction",
    "scriptHookId": null,
    "normalIdleTimers": true,
    "defaultAssumptionIds": [
      "gray_hoverboard",
      "green_fuzz",
      "green_fuzz_carbon",
      "blue_slightdmg"
    ],
    "source": {
      "archiveSha256": "026da208cdf7fdec6e09491f1262d271af3dd67a571ce8bf583f73435f9fb602",
      "applicationVersion": "1.0.5 Demo",
      "asset": "resources.assets",
      "storeEventPathId": 24360,
      "itemPathId": 24609,
      "characterPathId": 23844
    },
    "reason": "Exact native item definition + explicit day + matching player-buy direction; Character identity is the serialized pointer. Full-video build equivalence is not claimed."
  },
  "day11-darcy-close": {
    "visitId": "day11-darcy-close",
    "status": "not-applicable",
    "eventId": null,
    "itemDefinitionId": null,
    "characterId": null,
    "personality": null,
    "initialAskingPrice": null,
    "openingAskStatus": "not-established",
    "initialModifier": "unknown",
    "scriptHookId": null,
    "normalIdleTimers": null,
    "defaultAssumptionIds": [],
    "source": null,
    "reason": "This recorded visit is a story/gift. A trading personality is not established or required for this row."
  }
};
export function getDemoCustomer(visitId: string): DemoCustomerFacts {
  return structuredClone(DEMO_CUSTOMER_FACTS[visitId] ?? {
    visitId, status: 'unknown', eventId: null, itemDefinitionId: null, characterId: null,
    personality: null, initialAskingPrice: null, openingAskStatus: 'not-established',
    initialModifier: 'unknown', scriptHookId: null, normalIdleTimers: null,
    defaultAssumptionIds: [], source: null, reason: 'No explicit source binding for this visit.'
  });
}
