import type {CurationState} from './native-curation';
import {nativeHammerValue,isNativeTrulyValuable} from './native-generation';
import type {RentalRequest} from './native-rental';
/** Operating rules independently implemented from Windows 1.0.5 managed probes. */
import {createScheduler,randomUnit,type Contexts,type SchedulerState} from './native-scheduler';
import type {StoryState} from './native-story';
export interface RentalRecord {id:string;itemId:string;startDay:number;days:number;price:number;dueDay:number;status:'active'|'returned'|'lost'|'delayed';damage:number;compensation:number;}
export interface AuctionRecord {id:string;itemId:string;enteredDay:number;readyDay:number;hammer:number;commission:number;proceeds:number;collected:boolean;}
export interface ChallengeProgress {purchaseAttempts:number;saleAttempts:number;bought:number;sold:number;correct:number;goodBuy:number;goodSell:number;streetStops:number;scored:boolean;score:number;cashScore?:number;soldMarginTotal?:number;remainingBeforeLiquidation?:number;contentScope:string;}
export interface NativeWorld {version:1;contexts:Contexts;curation?:CurationState|null;streetRepairIds?:string[];streetAuctionId?:string;streetPurchases?:{id:string;storeId:string;day:number;price:number;productNumber:number;alreadyOwned:boolean}[];lastStreetPurchase?:{id:string;lines:string[]};scheduler:SchedulerState;story:StoryState|null;suspendedStories?:StoryState[];activeSourceEvent:string|null;activeItemDefinition:string|null;eventPhase:'intro'|'haggle'|'outro'|'none';flower:{type:number;life:number;display:number[]};repair:{usedDay:number;used:boolean};auctions:AuctionRecord[];rentals:RentalRecord[];rentalRequest?:RentalRequest|null;rentalDecisions?:{day:number;accepted:boolean}[];rentalRequests:number;rentalAccepted:number;rentalFirstDay:number|null;auctionWeek:number;auctionCount:number;visitors:number;reportWeek:number;reportTotal:number;estates:number[];balances:number[];weeklyProfit:number;journal:{id:string;text:string;day:number}[];calendar:{id:string;text:string;start:number;interval:number;end:number|null;checked:boolean}[];signals:string[];limitations:string[];challenge:ChallengeProgress|null;rng:number;generationChoiceRng?:number;generationHistory?:{day:number;itemId:string;wrong:boolean|null}[];lastGeneration?:{branch:string;eligibleIds:string[];target:number|null};redCardRolls?:{once:number;last:number;report:number};}
export function createWorld(seed:number,day=1):NativeWorld{return {version:1,contexts:{},scheduler:createScheduler(seed),story:null,activeSourceEvent:null,activeItemDefinition:null,eventPhase:'none',flower:{type:0,life:0,display:[1,2,3]},repair:{usedDay:day,used:false},auctions:[],rentals:[],rentalRequests:0,rentalAccepted:0,rentalFirstDay:null,auctionWeek:Math.floor((day-1)/5),auctionCount:0,visitors:0,reportWeek:0,reportTotal:0,estates:[],balances:[],weeklyProfit:0,journal:[],calendar:[],signals:[],limitations:[],challenge:null,rng:seed>>>0};}
export const FLOWERS=[{type:1,name:'Horong',price:50,effect:'Changes Active and Wishy-Washy opening offers.'},{type:2,name:'Bomi',price:60,effect:'Adds 0.3 to the visitor increment.'},{type:3,name:'Dora',price:50,effect:'Changes non-Fixie impatience and waiting behavior.'},{type:4,name:'Adam',price:80,effect:'May change an item’s condition when its true and customer condition agree.'},{type:5,name:'Hoochoo',price:70,effect:'The supplied Demo implements purchase and lifespan; its advertised forgetting benefit has no verified execution path.'},{type:6,name:'Hari',price:130,effect:'Combines visitor and patience effects; absent from the ordinary random flower selection.'}] as const;
export function flowerDisplay(w:NativeWorld,day:number){if(day<6){w.flower.display=[1,2,3];return;}const pool=[1,2,3,4,5].filter(n=>n!==w.flower.type);const out:number[]=[];while(out.length<3&&pool.length)out.push(pool.splice(Math.floor(randomUnit(w)*pool.length),1)[0]);w.flower.display=out;}
export function visitorIncrement(input:{day:number;displayCount:number;distinctGray:number;appraisedTier:number;recommendedTier:number;sameGrayAsRecommended:number;flowerType:number;flowerLife:number;brokenLevel:number;topReporter:boolean}){
 const i=input;let n=(i.day===1?.2:.4)+i.displayCount/64+(i.distinctGray>8?.1:0)+(i.appraisedTier>=2?.1:0)+(i.recommendedTier>=2?.1:0)+i.sameGrayAsRecommended*.05+(i.flowerLife>0&&[2,6].includes(i.flowerType)?.3:0);if(i.brokenLevel>=2||i.topReporter)n/=2;return n;
}
export function reportScore(day:number,todayBefore:number,weekBefore:number){return todayBefore>4?0:Math.trunc((14+8*todayBefore-2*(day%5))/2**todayBefore)+Math.trunc((10+8*weekBefore)/2**weekBefore);}
export function housingRent(day:number){return day<31?200:270;}
export function isBroke(cash:number,trueInventory:number){return Math.trunc(cash+trueInventory)<=99;}
export function ageCardIds(ids:string[],preserveHurtTransition=false){let list=ids.map(id=>id==='blue_junkpotential'?'blue_junkpotential1':id==='blue_junkpotential1'?'blue_novalue2':id==='blue_superstitious'?'blue_superstitious1':id==='blue_superstitious1'?'blue_superstitious2':id);if(ids.includes('blue_superstitious2')&&!list.includes('blue_reput_hurt'))list=[...list.filter(id=>!id.startsWith('blue_pop')&&!id.startsWith('blue_unpop')),'blue_reput_hurt'];if(!preserveHurtTransition)list=list.map(id=>id==='blue_reput_hurt'?'blue_reput_hurt1':id);return list;}
export function adamCondition(current:string,w:{rng:number}){if(current==='blue_novalue')return 'blue_fairlydmg';if(current==='blue_perfect')return 'blue_slightdmg';if(current==='blue_fairlydmg')return randomUnit(w)<.6?'blue_slightdmg':'blue_novalue';if(current==='blue_slightdmg')return randomUnit(w)<.6?'blue_perfect':'blue_fairlydmg';return current;}
export function rentalParameters(day:number,firstDay:number|null,requests:number,accepted:number){const recentRatio=requests?accepted/requests:0;const old=firstDay!==null&&firstDay+3<day;return {unlockedAge:old,recentRatio,deactivated:old&&requests>=8&&recentRatio<=.1,inactive:old&&requests>=5&&recentRatio<=.2,maximum:old&&recentRatio>=.8?5:old&&recentRatio>=.55?4:old&&recentRatio>=.3?3:2,probability:old&&recentRatio>=.55?.7:.6,minPrice:old&&recentRatio>=.8?250:old&&recentRatio>=.55?350:500};}
export function rentalQuote(day:number,displayValue:number,listing:number,days:number){if(![2,3,4].includes(days)||day>=39&&days>2||day>=38&&days>3)return null;const fair=Math.trunc(Math.fround(Math.min(Math.trunc(displayValue),listing)*Math.fround({2:.34,3:.5,4:.67}[days]!)));return {days,fair,min:Math.trunc(Math.fround(fair*Math.fround(.85))),max:Math.trunc(Math.fround(fair*Math.fround(1.15)))};}
export function rentalReturn(record:RentalRecord,trueValue:number,playerCondition:string,w:{rng:number}){const r={...record};if(randomUnit(w)<.9){r.status='returned';const p=randomUnit(w);r.damage=r.days===4?p<.5?1:p<.75?2:0:p<.3?1:0;}else if(trueValue>=400||['blue_perfect','blue_slightdmg'].includes(playerCondition)){r.status='lost';r.compensation=r.price;}else{r.status='delayed';r.dueDay++;}return r;}
export function auctionEligibility(ids:string[]){return !ids.includes('blue_repaired')&&!ids.includes('blue_totallyWrecked')&&isNativeTrulyValuable(ids);}
export function auctionResult(value:number,ids:string[],week:number,w:{rng:number}){const entryFee=week<5?300:450,result=nativeHammerValue(value,ids,()=>randomUnit(w)),hammer=Math.trunc(result.value);const commission=Math.trunc(Math.fround(Math.fround(hammer)*Math.fround(week<5?.05:.08)));return {entryFee,hammer,commission,proceeds:hammer-commission,band:result.band};}
/** Source successfulSell40 accidentally counts purchases at <=1.4 of truth; preserve this marked quirk. */
export function challengeScore(c:ChallengeProgress){let total=(c.cashScore??0)+(c.correct+c.goodBuy+c.goodSell)*50;if(c.bought===30)total*=2;if(c.bought>0&&c.remainingBeforeLiquidation===0)total*=2;if(c.bought>0&&c.correct===c.bought)total*=3;if(c.sold>0&&(c.soldMarginTotal??0)/c.sold>=1.4)total*=3;return total;}
