import {NATIVE_MANUAL_FRAME,NATIVE_MANUAL_PAGES} from './native-manual-data';
import {resolveNativePickupCard} from './native-rules';
import {drawNativeText,layoutNativeText,type TextRect} from './native-text';
import {testCondition,type Contexts} from './native-scheduler';
import type {NativeManualNode,NativeManualPage} from './native-types';

export interface ManualHit {id:string;label:string;rect:TextRect;cardId?:string;pageId?:string;action?:'home'|'previous'|'next'|'close';disabled?:boolean}
type Size=[number,number];
const pages=new Map(NATIVE_MANUAL_PAGES.map(p=>[p.id,p]));
export const MANUAL_ALIASES:Record<string,string>={index:'Home',condition:'Status',materials:'Materials',gem:'Jewel',jewels:'Jewel',signatures:'Signatures','tools-damage':'Tools_Integrity','tools-year':'Tools_Year',year:'Historic','watch-movement':'WatchMovement',material:'Materials','brand-list':'BrandsMain 1','brand-easy-enough':'Brands_EasyEnough','brand-fxxx-fxxx':'Brands_FxxxFxxx','brand-wildcards':'BrandsMain','celebrity-types':'Signatures','celebrity-index':'FigureList','celebrity-ahn-lee':'Figures13','celebrity-gong-han':'Figures3','celebrity-hwang-kim':'Figures6','celebrity-emily-semilia':'Figures7','celebrity-lee-choi':'Figures11','celebrity-moo-mo':'Figures12',history:'Historic','chronology-recent':'History_Timeline2','history-anti-chippie':'MajorEvent_Conflict_AntiChippieLaw','history-fiber-10':'MajorEvent_Monsoon_FixerLaunch',artwork:'Artwork','artwork-help':'Artwork'};
export function nativePage(id:string){return pages.get(MANUAL_ALIASES[id]??id)??pages.get('Home')!;}
export function availableManualPages(contexts:Contexts){return NATIVE_MANUAL_PAGES.filter(p=>testCondition(p.unlockCondition,contexts));}
export function adjacentManualPage(id:string,dir:number,contexts:Contexts){const list=availableManualPages(contexts),at=list.findIndex(p=>p.id===nativePage(id).id);return list[Math.max(0,Math.min(list.length-1,at+dir))]?.id??'Home';}
function predicate(c:any,contexts:Contexts){
 if(!c.useComplex)return testCondition(c.predicate,contexts);
 const x=c.complex??{},list=(v:unknown):string[]=>Array.isArray(v)?v:typeof v==='string'&&v.trim()?v.split(/[;,]/).filter(Boolean):[];
 const all=list(x.trueIfAllOf),any=list(x.trueIfAnyOf),notAll=list(x.falseIfAllOf),notAny=list(x.falseIfAnyOf);
 let result=!all.length&&!any.length;
 if(all.length)result=all.every(p=>testCondition(p,contexts));if(any.some(p=>testCondition(p,contexts)))result=true;
 if(notAll.length&&notAll.every(p=>testCondition(p,contexts)))result=false;if(notAny.some(p=>testCondition(p,contexts)))result=false;return result;
}

const imageTints=new Map<string,HTMLCanvasElement>();
function tintImage(image:HTMLImageElement,color:string):CanvasImageSource{
 if(color.slice(0,7).toLowerCase()==='#ffffff')return image;const key=image.src+color.slice(0,7);let canvas=imageTints.get(key);if(canvas)return canvas;
 canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const c=canvas.getContext('2d')!;c.drawImage(image,0,0);const data=c.getImageData(0,0,canvas.width,canvas.height),rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255);for(let i=0;i<data.data.length;i+=4){data.data[i]*=rgb[0];data.data[i+1]*=rgb[1];data.data[i+2]*=rgb[2];}c.putImageData(data,0,0);imageTints.set(key,canvas);return canvas;
}

/** Rebuild Unity's rect and layout-group geometry before drawing; serialized driven rects are not final geometry. */
export class NativeManualView {
 hits:ManualHit[]=[];bounds:{id:string;rect:TextRect}[]=[];private visibility=new Map<string,boolean>();private contexts:Contexts={};private disabled=new Map<string,boolean>();private imageVisible=new Map<string,boolean>();private textVisible=new Map<string,boolean>();private clips:TextRect[]=[];private pointer:Size=[-1,-1];private scrollOffsets=new Map<string,number>();private scrollRegions:{id:string;rect:TextRect;max:number}[]=[];private contentOffsets=new Map<string,number>();private hoverStay=new Map<string,TextRect[]>();private hoverRegions:{rect:TextRect;target:string}[]=[];
 setPointer(x:number,y:number){this.pointer=[x,y];}
 wheel(deltaY:number,x=this.pointer[0],y=this.pointer[1]){const r=[...this.scrollRegions].reverse().find(r=>x>=r.rect[0]&&x<=r.rect[0]+r.rect[2]&&y>=r.rect[1]&&y<=r.rect[1]+r.rect[3]);if(!r||r.max<=0)return false;this.scrollOffsets.set(r.id,Math.max(0,Math.min(r.max,(this.scrollOffsets.get(r.id)??0)+deltaY)));return true;}private page!:NativeManualPage;
 get pageId(){return this.page?.id??'Home';}
 constructor(private image:(path:string)=>HTMLImageElement){}
 private active(n:NativeManualNode){return (this.visibility.get(n.id)??(n.active&&n.canvas?.enabled!==false))&&!(n.conditions??[]).some(c=>c.kind==='ExistByContext'&&!predicate(c,this.contexts));}
 private prepare(n:NativeManualNode){for(const c of n.conditions??[]){if(c.kind==='EnableByContext')for(const target of c.targets??[]){if(!target.nodeId)continue;const enabled=predicate(c,this.contexts)!==target.invert;if(target.type.startsWith('gameObjects'))this.visibility.set(target.nodeId,enabled);else if(target.targetClass==='Button'||target.targetClass==='EventRichButton')this.disabled.set(target.nodeId,!enabled);else if(target.targetClass?.startsWith('TextMeshPro'))this.textVisible.set(target.nodeId,enabled);else if(['Image','RawImage','SpriteRenderer'].includes(target.targetClass??''))this.imageVisible.set(target.nodeId,enabled);}}n.children.forEach(c=>this.prepare(c));}
 private hit(hit:ManualHit){let r=hit.rect;for(const clip of this.clips){const x=Math.max(r[0],clip[0]),y=Math.max(r[1],clip[1]);r=[x,y,Math.max(0,Math.min(r[0]+r[2],clip[0]+clip[2])-x),Math.max(0,Math.min(r[1]+r[3],clip[1]+clip[3])-y)];}if(r[2]>0&&r[3]>0)this.hits.push({...hit,rect:r});}
 private children(n:NativeManualNode){return n.children.filter(c=>this.active(c)&&!c.layoutElement?.ignore);}
 private preferred(n:NativeManualNode,width=Infinity):Size{
  if(!Number.isFinite(width)&&n.rect.sizeDelta[0]>0&&n.fitter?.vertical)width=n.rect.sizeDelta[0];
  let w=0,h=0;if(n.image?.sprite){w=n.image.sprite.width;h=n.image.sprite.height;}
  if(n.text){const m=layoutNativeText(n.text,width,this.contexts);w=Math.max(w,m.width+n.text.margins[0]+n.text.margins[2]);h=Math.max(h,m.height+n.text.margins[1]+n.text.margins[3]);}
  const g=n.layout;if(g){const [l,t,r,b]=g.padding,children=this.children(n),spacing=typeof g.spacing==='number'?g.spacing:0;
   if(g.type==='grid'){const [cw,ch]=g.cellSize??[100,100],sp=Array.isArray(g.spacing)?g.spacing:[g.spacing,g.spacing],cols=g.constraint===1?g.constraintCount??1:g.constraint===2?Math.ceil(children.length/(g.constraintCount??1)):Math.max(1,Math.floor((width-l-r+sp[0])/(cw+sp[0])));w=l+r+Math.min(children.length,Number.isFinite(cols)?cols:children.length)*(cw+sp[0])-sp[0];h=t+b+Math.ceil(children.length/(Number.isFinite(cols)?cols:children.length))*(ch+sp[1])-sp[1];}
   else{const sizes=children.map(c=>{const p=this.preferred(c,g.type==='vertical'?g.controlWidth?Math.max(1,width-l-r):c.rect.sizeDelta[0]>0?c.rect.sizeDelta[0]:Math.max(1,width-l-r):c.fitter?.vertical&&c.rect.sizeDelta[0]>0?c.rect.sizeDelta[0]:Infinity);return [g.controlWidth||c.fitter?.horizontal?p[0]:c.rect.sizeDelta[0],g.controlHeight||c.fitter?.vertical?p[1]:c.rect.sizeDelta[1]] as Size;});w=l+r+(g.type==='horizontal'?sizes.reduce((a,s)=>a+s[0],0)+Math.max(0,sizes.length-1)*spacing:Math.max(0,...sizes.map(s=>s[0])));h=t+b+(g.type==='vertical'?sizes.reduce((a,s)=>a+s[1],0)+Math.max(0,sizes.length-1)*spacing:Math.max(0,...sizes.map(s=>s[1])));}
  }
  const e=n.layoutElement;if(e){if(e.preferredWidth>=0)w=e.preferredWidth;if(e.preferredHeight>=0)h=e.preferredHeight;w=Math.max(w,e.minWidth);h=Math.max(h,e.minHeight);}return [Math.max(0,w),Math.max(0,h)];
 }
 private box(n:NativeManualNode,parent:Size):TextRect{const r=n.rect,w=(r.anchorMax[0]-r.anchorMin[0])*parent[0]+r.sizeDelta[0],h=(r.anchorMax[1]-r.anchorMin[1])*parent[1]+r.sizeDelta[1];const p=this.preferred(n,w||Infinity),size:Size=[n.fitter?.horizontal?p[0]:w,n.fitter?.vertical?p[1]:h];return [(r.anchorMin[0]+(r.anchorMax[0]-r.anchorMin[0])*r.pivot[0])*parent[0]+r.anchoredPosition[0]-size[0]*r.pivot[0],(1-r.anchorMin[1]-(r.anchorMax[1]-r.anchorMin[1])*r.pivot[1])*parent[1]-r.anchoredPosition[1]-size[1]*(1-r.pivot[1]),...size];}
 private layoutChildren(n:NativeManualNode,size:Size):Map<string,TextRect>{
  const out=new Map<string,TextRect>(),g=n.layout;if(!g)return out;const children=this.children(n);if(g.reverse)children.reverse();const [l,t,r,b]=g.padding,inner:Size=[size[0]-l-r,size[1]-t-b],align:Size=[g.alignment%3/2,Math.floor(g.alignment/3)/2];
  if(g.type==='grid'){const [w,h]=g.cellSize??[100,100],[sx,sy]=Array.isArray(g.spacing)?g.spacing:[g.spacing,g.spacing],cols=g.constraint===1?g.constraintCount??1:g.constraint===2?Math.ceil(children.length/(g.constraintCount??1)):Math.max(1,Math.floor((inner[0]+sx+.001)/(w+sx))),rows=g.constraint===2?g.constraintCount??1:Math.ceil(children.length/cols);const ox=l+(inner[0]-Math.min(cols,children.length)*(w+sx)+sx)*align[0],oy=t+(inner[1]-rows*(h+sy)+sy)*align[1];children.forEach((c,i)=>{let col=g.startAxis===1?Math.floor(i/rows):i%cols,row=g.startAxis===1?i%rows:Math.floor(i/cols);if((g.startCorner??0)%2)col=cols-1-col;if((g.startCorner??0)>1)row=rows-1-row;out.set(c.id,[ox+col*(w+sx),oy+row*(h+sy),w,h]);});return out;}
  const axis=g.type==='horizontal'?0:1,cross=1-axis,spacing=Number(g.spacing),control=[g.controlWidth,g.controlHeight],expand=[g.expandWidth,g.expandHeight];
  const prefs=children.map(c=>this.preferred(c,axis===1?inner[0]:Infinity));const sizes=children.map((c,i)=>[0,1].map(a=>control[a]||(a===0?c.fitter?.horizontal:c.fitter?.vertical)?prefs[i][a]:c.rect.sizeDelta[a]) as Size);
  const total=sizes.reduce((sum,s)=>sum+s[axis],0)+spacing*Math.max(0,children.length-1),flex=children.map(c=>Math.max(expand[axis]?1:0,axis===0?c.layoutElement?.flexibleWidth??0:c.layoutElement?.flexibleHeight??0)),flexTotal=flex.reduce((a,b)=>a+b,0),extra=Math.max(0,inner[axis]-total);let pos=(axis===0?l:t)+(flexTotal?0:extra*align[axis]);
  children.forEach((c,i)=>{const s=sizes[i];if(control[axis]&&flexTotal)s[axis]+=extra*flex[i]/flexTotal;if(control[cross]&&expand[cross])s[cross]=Math.max(s[cross],inner[cross]);const crossPos=(cross===0?l:t)+(inner[cross]-s[cross])*align[cross];out.set(c.id,axis===0?[pos,crossPos,...s]:[crossPos,pos,...s]);pos+=s[axis]+spacing;});return out;
 }
 private worldRect(ctx:CanvasRenderingContext2D,r:TextRect):TextRect{const t=ctx.getTransform(),a=new DOMPoint(r[0],r[1]).matrixTransform(t),b=new DOMPoint(r[0]+r[2],r[1]+r[3]).matrixTransform(t);return [Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y)];}
 private drawNode(ctx:CanvasRenderingContext2D,n:NativeManualNode,parent:Size,forced?:TextRect){
  if(!this.active(n))return;const [x,y,w,h]=forced??this.box(n,parent);ctx.save();ctx.translate(x+w*n.rect.pivot[0],y+h*(1-n.rect.pivot[1])-(this.contentOffsets.get(n.id)??0));ctx.scale(...n.rect.scale);ctx.rotate(-n.rect.rotation*Math.PI/180);ctx.translate(-w*n.rect.pivot[0],-h*(1-n.rect.pivot[1]));this.bounds.push({id:n.id,rect:this.worldRect(ctx,[0,0,w,h])});
  if(n.mask){ctx.beginPath();ctx.rect(0,0,w,h);ctx.clip();this.clips.push(this.worldRect(ctx,[0,0,w,h]));}const sprite=n.image?.sprite;
  if(n.image&&w>0&&h>0&&this.imageVisible.get(n.id)!==false){
   if(sprite){const im=this.image(sprite.asset);if(im.complete&&im.naturalWidth){ctx.save();ctx.globalAlpha*=parseInt(n.image.color.slice(7,9)||'ff',16)/255;const source=tintImage(im,n.image.color);if(n.image.preserveAspect){const factor=Math.min(w/im.naturalWidth,h/im.naturalHeight);ctx.drawImage(source,(w-im.naturalWidth*factor)/2,(h-im.naturalHeight*factor)/2,im.naturalWidth*factor,im.naturalHeight*factor);}else if(n.image.type===1&&sprite.border?.some(v=>v>0)){const [l,b,r,t]=sprite.border,scale=100/(sprite.pixelsPerUnit??100)/(n.image.pixelsPerUnitMultiplier??1),factorX=Math.min(1,w/((l+r)*scale||1)),factorY=Math.min(1,h/((t+b)*scale||1)),xs=[0,l,im.naturalWidth-r,im.naturalWidth],ys=[0,t,im.naturalHeight-b,im.naturalHeight],dx=[0,l*scale*factorX,w-r*scale*factorX,w],dy=[0,t*scale*factorY,h-b*scale*factorY,h];for(let row=0;row<3;row++)for(let col=0;col<3;col++)if((row!==1||col!==1||n.image.fillCenter)&&xs[col+1]>xs[col]&&ys[row+1]>ys[row])ctx.drawImage(source,xs[col],ys[row],xs[col+1]-xs[col],ys[row+1]-ys[row],dx[col],dy[row],dx[col+1]-dx[col],dy[row+1]-dy[row]);}else ctx.drawImage(source,0,0,w,h);ctx.restore();}}
   else {ctx.fillStyle=n.image.color;ctx.fillRect(0,0,w,h);}
  }
  for(const a of n.actions??[])if(a.eventType===1&&a.method==='set_enabled'&&a.targetClass==='Canvas'&&!a.boolValue&&a.targetNodeId){const rect=this.worldRect(ctx,[0,0,w,h]);this.hoverStay.set(a.targetNodeId,[...(this.hoverStay.get(a.targetNodeId)??[]),rect]);this.hits=this.hits.filter(hit=>!hit.cardId||hit.rect[0]+hit.rect[2]<=rect[0]||hit.rect[0]>=rect[0]+rect[2]||hit.rect[1]+hit.rect[3]<=rect[1]||hit.rect[1]>=rect[1]+rect[3]);}
  if(n.text&&this.textVisible.get(n.id)!==false){const links=drawNativeText(ctx,n.text,[0,0,w,h],this.image,this.contexts,n.name==='PageTitle'?this.page.title:undefined,n.linkColors);if(n.dragTextLinks)for(const [i,link] of links.entries()){const id=resolveNativePickupCard(link.id.replace(/^c:/,''),Number(this.contexts['PickupMaterial.ID']??0));this.hit({id:`native-link-${n.id}-${i}`,label:link.label,rect:this.worldRect(ctx,link.rect),...(link.id.startsWith('p:')?{pageId:link.id.slice(2)}:{cardId:id})});}}
  const dest=n.actions?.find(a=>a.method==='Raise'&&a.stringValue&&pages.has(a.stringValue))?.stringValue,method=n.actions?.map(a=>a.method)??[];
  const action=method.includes('GotoMenuPage')?'home':method.includes('GotoLeftPage')?'previous':method.includes('GotoRightPage')?'next':n.name==='CloseButton'?'close':undefined;
  for(const a of n.actions??[])if(a.eventType===0&&a.method==='set_enabled'&&a.targetClass==='Canvas'&&a.boolValue&&a.targetNodeId)this.hoverRegions.push({rect:this.worldRect(ctx,[0,0,w,h]),target:a.targetNodeId});
  if(n.cardId||dest||action)this.hit({id:`native-book-${n.id}`,label:n.text?.text.replace(/<[^>]*>/g,'')||dest||action||n.cardId||n.name,rect:this.worldRect(ctx,[0,0,w,h]),cardId:n.cardId?resolveNativePickupCard(n.cardId,Number(this.contexts['PickupMaterial.ID']??0)):undefined,pageId:dest,action,disabled:this.disabled.get(n.id)||!!dest&&!testCondition(pages.get(dest)!.unlockCondition,this.contexts)});
  if(n.id===NATIVE_MANUAL_FRAME.pageContainerId)this.drawNode(ctx,this.page.root,[w,h],[0,0,w,h]);else{const layout=this.layoutChildren(n,[w,h]);let skip:string[]=[];
   if(n.scroll){const scroll=n.scroll,viewport=n.children.find(c=>c.id===scroll.viewportId),content=viewport?.children.find(c=>c.id===scroll.contentId);if(viewport&&content){const pref=this.preferred(content,w),max=scroll.vertical?Math.max(0,pref[1]-h):0,offset=Math.min(this.scrollOffsets.get(n.id)??0,max);layout.set(viewport.id,[0,0,w,h]);this.contentOffsets.set(content.id,offset);this.scrollRegions.push({id:n.id,rect:this.worldRect(ctx,[0,0,w,h]),max});skip=[scroll.horizontalScrollbarId??'',scroll.verticalScrollbarId??''];}}
   for(const child of n.children)if(!skip.includes(child.id))this.drawNode(ctx,child,[w,h],layout.get(child.id));}if(n.mask)this.clips.pop();ctx.restore();
 }
 render(ctx:CanvasRenderingContext2D,id:string,contexts:Contexts){const requested=nativePage(id);this.page=testCondition(requested.unlockCondition,contexts)?requested:this.page&&testCondition(this.page.unlockCondition,contexts)?this.page:nativePage('Home');this.contexts=contexts;this.hits=[];this.visibility.clear();for(const r of this.hoverRegions){const [x,y]=this.pointer;const bounds=[r.rect,...(this.hoverStay.get(r.target)??[])];if(bounds.some(b=>x>=b[0]&&x<=b[0]+b[2]&&y>=b[1]&&y<=b[1]+b[3]))this.visibility.set(r.target,true);}this.hoverRegions=[];this.hoverStay.clear();this.bounds=[];this.disabled.clear();this.imageVisible.clear();this.textVisible.clear();this.clips=[];this.scrollRegions=[];this.contentOffsets.clear();this.prepare(this.page.root);this.prepare(NATIVE_MANUAL_FRAME.root);this.drawNode(ctx,NATIVE_MANUAL_FRAME.root,[1920,1080],[1350,154,570,801]);return this.hits;}
}
