import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,type Stock} from './engine';
import {NATIVE_CAMPAIGN} from './native-campaign-data';
import {createScheduler,scheduleDay,triggeredEvent,evaluateExpression,type SourceEvent,type CampaignCatalog} from './native-scheduler';
import {advanceStory,createStory} from './native-story';
import {createWorld,reportScore,visitorIncrement,housingRent,isBroke,rentalQuote,auctionResult,challengeScore} from './native-services';
import {getNativeItem,createNativeItem} from './native-rules';
import {validateCashbook} from './accounting';
const event=(id:string,overrides:Partial<SourceEvent>={}):SourceEvent=>({id,sourceId:id,eventType:2,condition:'',triggerCondition:'',repeatable:false,triggerCountdown:0,triggerCancel:false,startingContexts:[],doHaggle:false,playerCanDecline:true,item:null,itemFromContext:null,customer:null,personality:1,defaultCards:[],intro:[],outro:[],chunks:{},acceptableItems:[],requiredCards:[],cardMode:'all',...overrides});
function drive(g:Game,limit=2400){for(let step=0;step<limit&&!g.state.completed&&!g.state.failure;step++){
 if(g.state.phase==='narrative'){if(g.storyView.choices.length)g.chooseStory(g.storyView.choices[0].id);else if(g.storyView.waiting){const w=g.storyView.waiting;if(w.requirement)for(const i of g.state.stock)g.listStock(i.id,i.value,0);g.signalStory(w.name,w.requirement&&!w.requirement.includes('==')?w.requirement:undefined);g.signalStory('StockOpened');g.continueStory();}else g.continueStory();}
 else if(g.active){if(g.curationView&&g.curationView.stage!=='settled'){if(g.curationView.stage==='select'){const item=g.getCurationCandidates()[0];if(item)g.submitCurationItem(item.id);else g.declineCuration();}else if(g.curationView.stage==='counter')g.acceptCurationCounter();else g.offerCurationPrice(1);continue;}const script=g.state.negotiation?.native.script?.kind;if(script==='D011HaggleDarcy'){if(g.state.counter!==null)g.accept();else{g.state.quote='190';g.offer();}continue;}if(script==='D012StockHue'){g.state.quote='40';g.offer();continue;}if(script==='D02FirstassessCondition'&&g.state.negotiation!.native.script!.cardActive){g.inspect('damage');g.add(g.cardsFromNative(['blue_fairlydmg'])[0]);continue;}if(script==='D03FirstassessMaterialAfter'){g.inspect('material');g.add(g.cardsFromNative(['green_24kGold'])[0]);continue;}g.state.quote=String(Math.min(g.state.cash,Math.ceil((g.state.negotiation?.publicValue??0)*.9)));if(g.visit.side==='buy')g.offer();else g.beginSale();if(!g.world.story&&g.active&&g.state.counter!==null&&g.state.counter<=g.state.cash)g.accept();if(!g.world.story&&g.active)g.decline();}
 else if(g.state.phase==='between')g.nextDay();else {for(const i of g.state.stock)if(i.listing===null)g.listStock(i.id,i.value);g.next();}
 assert.ok(validateCashbook(g.state.openingCash,g.state.cash,g.state.cashbook));assert.equal(new Set(g.state.stock.map(i=>i.id)).size,g.state.stock.length);
}assert.equal(g.state.completed,true,JSON.stringify(g.storyView));}
test('source bootstrap is 1000 cash, 1500 debt at 1%, no inferred video inventory',()=>{const g=new Game([]);g.start([],'demo');assert.equal(g.state.cash,1000);assert.equal(g.state.day,1);assert.equal(g.state.stock.length,0);assert.deepEqual(g.state.reputationState,{expertnessRaw:0,attractivenessRaw:0,wittinessRaw:0});assert.deepEqual(g.state.loans[0],{id:'darcy',principal:1500,rate:.01,cycleDays:1,startedDay:1,status:'active',overdue:0});assert.equal(g.visit.sourceEventId,'D01_1_haggle_darcy');});
test('source scheduler distributes four purchases and interposes possible sale/rental/trigger opportunities',()=>{const s=createScheduler(2);assert.equal(scheduleDay(s,NATIVE_CAMPAIGN,1),true);assert.equal(s.queue.filter(x=>x==='@purchase').length,4);assert.deepEqual(s.queue.slice(0,2),['D01_1_haggle_darcy','D01_radio_avac_first']);assert.ok(s.queue.includes('@rental-returns'));assert.equal(s.queue.at(-1),'@day-end');assert.equal(scheduleDay(s,NATIVE_CAMPAIGN,2,3),true);assert.equal(s.queue.filter(x=>x==='@purchase').length,2);assert.equal(scheduleDay(s,NATIVE_CAMPAIGN,15),false);});
test('trigger counters advance for every candidate, priority selects first and canceled condition resets',()=>{const s=createScheduler(),a=event('a',{triggerCondition:'ready',triggerCountdown:1}),b=event('b',{triggerCondition:'ready',triggerCountdown:1,triggerCancel:true});const c={...NATIVE_CAMPAIGN,events:{a,b},levels:{triggeredEvents:{...NATIVE_CAMPAIGN.levels.triggeredEvents,schedule:['a','b']}}};assert.equal(triggeredEvent(s,c,{ready:true}),null);assert.equal(triggeredEvent(s,c,{ready:false})?.id,'a');assert.equal(s.countdowns.b,0);s.played.push('a');assert.equal(triggeredEvent(s,c,{ready:true}),null);assert.equal(triggeredEvent(s,c,{ready:true})?.id,'b');});
test('expression parser handles source context expressions without executing JavaScript',()=>{assert.equal(evaluateExpression('day>=3 && (n+2)*3==15',{day:3,n:3}),true);assert.equal(evaluateExpression('!unknown || false',{}),true);assert.equal(evaluateExpression("'a'+'b'",{}),'ab');assert.equal(evaluateExpression('process.exit(1)',{}),false);});
test('branch decisions occur after earlier effects, choices apply only selected operations and resume after JSON serialization',()=>{const ctx:Record<string,any>={n:0};let cash=0;const e=event('branch',{intro:[{type:'SetPersistentContextEventData',Key:'n',Value:'n+1'},{type:'BranchingEventData',predicate:'n==1',IfTrueEvents:[{type:'LineEventData',content:'Right branch'}],ElseEvents:[{type:'LineEventData',content:'Wrong branch'}]},{type:'TextChoiceEventData',choices:[{id:'a',LocalizedLabel:'A',onSelect:[{type:'AdjustBalanceEventData',amount:7}]},{id:'b',LocalizedLabel:'B',onSelect:[{type:'AdjustBalanceEventData',amount:999}]}]}]});let state=createStory(e,'intro',1);const host={contexts:()=>ctx,set:(k:string,v:any)=>ctx[k]=v,effect:(op:any)=>cash+=op.amount??0};advanceStory(state,host);assert.equal(state.line,'Right branch');advanceStory(state,host);assert.equal(cash,0);state=JSON.parse(JSON.stringify(state));advanceStory(state,host,'a');assert.equal(cash,7);advanceStory(state,host,'a');assert.equal(cash,7);});
test('daily bankruptcy uses true assets, report reward decays, rental accepts only native bounds',()=>{assert.equal(isBroke(0,100),false);assert.equal(isBroke(99.99,0),true);assert.equal(reportScore(11,0,0),22);assert.equal(reportScore(11,5,12),0);assert.equal(housingRent(30),200);assert.equal(housingRent(31),270);assert.deepEqual(rentalQuote(20,1000,900,2),{days:2,fair:306,min:260,max:351});assert.equal(rentalQuote(39,1000,1000,3),null);});
test('visitor flower 2 adds 0.3 before damaged-store halving; Hoochoo adds no unproved belief effect',()=>{const base={day:2,displayCount:0,distinctGray:0,appraisedTier:1,recommendedTier:1,sameGrayAsRecommended:0,flowerType:0,flowerLife:3,brokenLevel:0,topReporter:false};assert.equal(visitorIncrement(base),.4);assert.equal(visitorIncrement({...base,flowerType:2}),.7);assert.equal(visitorIncrement({...base,flowerType:2,brokenLevel:2}),.35);assert.equal(visitorIncrement({...base,flowerType:5}),.4);});
test('auction source nationalhis/national mismatch remains observable and fees use native float32 truncation',()=>{const plain=auctionResult(1000,[],1,{rng:7}),national=auctionResult(1000,['blue_nationalhis'],1,{rng:7});assert.deepEqual(plain,national);assert.equal(plain.entryFee,300);assert.equal(auctionResult(1000,[],5,{rng:7}).entryFee,450);assert.equal(plain.proceeds,plain.hammer-plain.commission);});
test('demo completes day1–3 with twelve generated purchases, balanced ledger, and resumes a live line identically',()=>{const a=new Game([]);a.start([],'demo',105);for(let i=0;i<12;i++)a.continueStory();const b=new Game([]);assert.deepEqual(b.restore(a.snapshot()),{ok:true});drive(a);drive(b);assert.deepEqual({...b.snapshot(),revision:0},{...a.snapshot(),revision:0});assert.equal(a.state.generatedVisits!.filter(v=>v.generated&&v.side==='buy').length,12);assert.deepEqual(a.state.closedDays,[1,2,3]);assert.equal(a.world.limitations.length,0);assert.equal(a.world.scheduler.played.includes('D03_hanja'),true);});
test('challenge executes 30 purchase attempts, five street stops, then a one-time native result',()=>{const g=new Game([]);g.start([],'challenge',99);drive(g);const c=g.world.challenge!;assert.equal(c.purchaseAttempts,30);assert.equal(c.streetStops,5);assert.equal(g.state.day,31);assert.equal(c.scored,true);assert.ok(c.contentScope.includes('day15'));const cash=g.state.cash,score=c.score;g.finish();assert.equal(g.state.cash,cash);assert.equal(c.score,score);});
test('repair batch capacity and daily service use survive reload, and repaired native facts change once',()=>{const g=new Game([]);g.start([],'challenge',1);const def=getNativeItem('EE_02')!;const make=(id:string):Stock=>({id,definitionId:def.id,title:def.name,paid:20,value:100,listing:null,cards:g.cardsFromNative(['gray_backpack','blue_fairlydmg','green_easyenough']),nativeItem:createNativeItem(def.id,{instanceId:id,cardIds:['gray_backpack','blue_fairlydmg','green_easyenough']})});g.state.stock=[make('a'),make('b'),make('c')];assert.equal(g.repairMany(['a','b','c']),false);assert.equal(g.repairMany(['a','b']),true);assert.equal(g.repairMany(['c']),false);assert.ok(g.state.stock[0].nativeItem!.cardIds.includes('blue_repaired'));const h=new Game([]);assert.deepEqual(h.restore(g.snapshot()),{ok:true});assert.equal(h.repair('c'),false);});
test('flower replacement pays exact source price and resets, never adds, lifespan',()=>{const g=new Game([]);g.start([],'challenge');const cash=g.state.cash;assert.equal(g.buyFlower(1),true);assert.equal(g.buyFlower(1),false);assert.equal(g.buyFlower(2),true);assert.equal(g.state.cash,cash-110);assert.equal(g.world.flower.life,3);});
test('challenge points include final cash and preserve source purchase-ratio sale-counter quirk',()=>{const c={purchaseAttempts:30,saleAttempts:30,bought:1,sold:0,correct:1,goodBuy:1,goodSell:1,streetStops:5,scored:false,score:0,cashScore:1000,remainingBeforeLiquidation:1,contentScope:''};assert.equal(challengeScore(c),(1000+150)*3);});

test('rental request creates an actual visitor and cheap quote transfers use, not ownership, exactly once',()=>{const g=new Game([]);g.start([],'demo',3);g.state.reputationState={expertnessRaw:135,attractivenessRaw:-40,wittinessRaw:0};g.refreshReputation();const def=getNativeItem('No_02')!;g.state.stock=[{id:'rental-item',definitionId:def.id,title:def.name,paid:10,value:900,listing:900,slot:0,cards:g.cardsFromNative(['gray_shoulderbag','blue_perfect']),nativeItem:createNativeItem(def.id,{instanceId:'rental-item'})}];g.world.story=null;g.state.phase='settled';for(let n=0;n<10&&!g.rentalRequestView;n++)g.considerRentalRequest();assert.ok(g.rentalRequestView);assert.equal(g.rentalRequestView!.tryPurchaseFirst,true);const cash=g.state.cash;g.state.quote='1';assert.equal(g.offer(),true);assert.equal(g.state.cash,cash+1);assert.equal(g.state.stock.length,1);assert.equal(g.state.stock[0].rented,true);assert.equal(g.acceptRental('rental-item',g.rentalRequestView!.days,1),false);assert.equal(g.state.cash,cash+1);assert.equal(g.world.rentalRequests,1);assert.equal(g.world.rentalAccepted,1);assert.equal(g.listStock('rental-item',100),false);});
test('player give-up runs original guidance chunk without ending incomplete D06 appraisal',()=>{const v={id:'day6-backpack-soldier',day:6,start:0,end:0,side:'buy' as const,title:'Backpack',base:0,initial:[],final:[],attractiveness:0,price:null,estimate:null,dialogues:[]};const g=new Game([v]);g.start();const cash=g.state.cash;assert.equal(g.requestDecline(),false);assert.equal(g.state.phase,'narrative');assert.equal(g.storyView.stage,'chunk');for(let n=0;n<30&&g.world.story;n++)g.continueStory();assert.equal(g.state.phase,'appraise');assert.equal(g.state.cash,cash);assert.equal(g.state.result,null);});

test('store scope allows tools during zero-extra-interaction waits and card waits match the exact payload',()=>{const g=new Game([]);g.start([],'demo');g.world.contexts['tool.brush']=true;g.world.activeSourceEvent='D02_firstassess_darcy';const e=NATIVE_CAMPAIGN.events.D02_firstassess_darcy;g.world.story=createStory(e,'intro',1);g.world.story.prepared=true;g.world.story.queue=[{type:'WaitGameplayEventData',GameplayEventToWait:{name:'ToolUsed_Integrity'},interactionsToAllow:0},{type:'WaitGameplayEventData',GameplayEventToWait:{name:'PlayerAssertCard'},interactionsToAllow:1,hasRequirement:true,requirement:'blue_slightdmg'},{type:'LineEventData',content:'Matched correct card'}];g.state.phase='narrative';g.continueStory();assert.equal(g.canInteract(128),true);assert.equal(g.canInteract(2),false);g.inspect('damage');assert.equal(g.storyView.waiting?.name,'PlayerAssertCard');g.signalStory('PlayerAssertCard','blue_perfect');g.continueStory();assert.equal(g.storyView.waiting?.name,'PlayerAssertCard');g.signalStory('PlayerAssertCard','blue_slightdmg');g.continueStory();assert.equal(g.storyView.line,'Matched correct card');});

test('manual story completion preserves the exact buyer and quitter contexts without an invented transfer',()=>{const g=new Game([]);g.start([],'demo');g.world.story=createStory(NATIVE_CAMPAIGN.events.D03_firstassess_material_after,'chunk',1,'gold');g.world.story.prepared=true;g.world.story.queue=[{type:'FinishPurchaseHaggleManually',itemBought:false,customerGaveUp:true,playerGaveUp:false}];g.world.story.returnPhase='appraise';g.state.phase='narrative';const cash=g.state.cash,stock=g.state.stock.length;g.continueStory();assert.equal(g.state.phase,'settled');assert.equal(g.getContext('customerGaveUp'),true);assert.equal(g.getContext('playerGaveUp'),false);assert.equal(g.getContext('itemBought'),false);assert.equal(g.state.cash,cash);assert.equal(g.state.stock.length,stock);});

test('a new private material fact preserves public belief and repeated assume toggles the private card',()=>{const v={id:'private-source-facts',definitionId:'No_02',day:11,start:0,end:0,side:'buy' as const,title:'Sample Bag',base:0,initial:[],final:[],attractiveness:0,price:null,estimate:null,dialogues:[]};const g=new Game([v]);v.initial=g.cardsFromNative(['gray_bag','green_fauxleather']) as never[];g.start();g.state.privateUnlocked=true;const card=g.cardsFromNative(['green_besch_cowhide'])[0],publicValue=g.estimate;assert.equal(g.add(card,true),true);assert.ok(g.nativeIds(g.state.tags).includes('green_fauxleather'));assert.equal(g.estimate,publicValue);assert.deepEqual(g.nativeIds(g.state.hidden),['green_besch_cowhide']);assert.equal(g.add(card,true),true);assert.equal(g.state.hidden.length,0);assert.equal(g.estimate,publicValue);});
