import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createCuration,curateNativeItem,priceNativeCuration,curationSuccessContexts} from './native-curation';
const rows=readFileSync(new URL('../reference/original-study/progression/curation-dll-fixtures.jsonl',import.meta.url),'utf8').trim().split('\n').map(x=>JSON.parse(x));
test('2,016 source DLL Curation selectors and price action sequences agree',()=>{let count=0;for(const r of rows){if(r.kind==='registry')continue;const c=createCuration(r.id,r.mode??'item',r.requirements??[]);c.declines=r.declined??0;const item={definitionId:r.definition,cardIds:r.ids,appraisalIds:r.appraisal,saleValue:r.value};const actual=r.kind==='item'?curateNativeItem(c,item):priceNativeCuration(c,item,r.price);assert.deepEqual(actual,r.actions,JSON.stringify(r));count++;}assert.equal(count,2016);});
test('source success effects only mutate the selected definition context',()=>{assert.deepEqual(curationSuccessContexts(createCuration('D14_preAvarice201','item',[]),'x'),{ItemForFixieWannabe1:'x'});assert.deepEqual(curationSuccessContexts(createCuration('D17_preAvarice202','item',[]),'y'),{ItemForFixieWannabe2:'y'});assert.deepEqual(curationSuccessContexts(createCuration('general','item',[]),'z'),{});});

import {Game,type Stock} from './engine';import {createNativeItem,getNativeItem} from './native-rules';import {validateCashbook} from './accounting';
function gameWithCuration(skip=false){const g=new Game([]);g.start([],'challenge',17);const def=getNativeItem('No_02')!,native=createNativeItem(def.id,{instanceId:'curation-stock'});const stock:Stock={id:native.instanceId,definitionId:def.id,title:def.name,nativeItem:native,paid:20,value:100,listing:null,cards:g.cardsFromNative(native.cardIds)};g.state.stock=[stock];g.world.story=null;g.world.activeSourceEvent=null;g.world.curation=createCuration('general','item',[def.id],skip);g.state.negotiation=null;return g;}
test('curation selects an unlisted owned instance, survives a pending line reload, and transfers cash and inventory once',()=>{const g=gameWithCuration(),cash=g.state.cash;assert.equal(g.getCurationCandidates()[0].listing,null);assert.equal(g.submitCurationItem('curation-stock'),true);assert.equal(g.curationView?.waiting,true);assert.equal(g.state.cash,cash);const h=new Game([]);assert.deepEqual(h.restore(g.snapshot()),{ok:true});h.continueStory();assert.equal(h.curationView?.stage,'price');assert.equal(h.offerCurationPrice(1),true);assert.equal(h.state.stock.length,1);h.continueStory();assert.equal(h.curationView?.stage,'settled');assert.equal(h.state.stock.length,0);assert.equal(h.state.cash,cash+1);assert.equal(h.acceptCurationCounter(),false);assert.equal(h.offerCurationPrice(1),false);assert.equal(h.getContext('Curation.sold'),true);assert.equal(validateCashbook(h.state.openingCash,h.state.cash,h.state.cashbook),true);});
test('source skip-haggle curation transfers the selected item for zero without an invented sale price',()=>{const g=gameWithCuration(true),cash=g.state.cash;g.submitCurationItem('curation-stock');g.continueStory();assert.equal(g.state.stock.length,0);assert.equal(g.state.cash,cash);assert.equal(g.getContext('Curation.soldPrice'),0);assert.equal(g.state.trades.at(-1)?.price,0);});
