#!/usr/bin/env python3
"""Export data, never decompiled implementation, for the 1.0.5 browser interpreter."""
import json,pathlib,collections
R=pathlib.Path(__file__).resolve().parents[2]; B=R/'reference/original-study/windows-1.0.5-demo'
idx={x['id']:x for x in json.loads((B/'final-index.json').read_text())}; ext=json.loads((B/'serialized-files.json').read_text())
cat=json.loads((R/'reference/original-study/progression/catalog-windows-1.0.5-demo.json').read_text())
tables={}
for t in json.loads((B/'localization-tables.json').read_text()):
 if t['locale']=='en-US':
  entries={str(e['key']):e['text'] for e in t['entries']}; entries.update({str(e['id']):e['text'] for e in t['entries']})
  tables[t['collection']]=entries
  if t.get('guid'):tables['GUID:'+t['guid']]=entries

def ptr(p,asset):
 p=p.get('$unity',p) if isinstance(p,dict) else {}
 if not p.get('m_PathID'): return None
 if p.get('m_FileID'):asset=pathlib.Path(ext[asset]['externals'][p['m_FileID']-1]).name
 ident=f"{asset}:{p['m_PathID']}";m=idx.get(ident,{})
 return {'ref':ident,'name':m.get('name',''),'class':m.get('class',m.get('type',''))}

def convert(n,asset,refs):
 if isinstance(n,list):return [convert(v,asset,refs) for v in n]
 if not isinstance(n,dict):return n
 if '$ref' in n:return convert(refs[n['$ref']],asset,refs)
 if '$array' in n:return convert(n['$array'],asset,refs)
 if '$unity' in n or 'm_FileID' in n and 'm_PathID' in n:return ptr(n,asset)
 t=n.get('$type','').split(',')[0]
 if t=='UnityEngine.Localization.LocalizedString' or 'm_TableReference' in n:
  table=n['m_TableReference']['m_TableCollectionName'];k=n['m_TableEntryReference']; key=k.get('m_Key') or str(k.get('m_KeyId',0));return tables.get(table,{}).get(key,'')
 return {**({'type':t} if t else {}),**{k:convert(v,asset,refs) for k,v in n.items() if not k.startswith('$')}}
def walk(n):
 if isinstance(n,dict):
  yield n
  for v in n.values():yield from walk(v)
 elif isinstance(n,list):
  for v in n:yield from walk(v)
events={}
for e in cat['storeEvents']:
 d=json.loads((R/e['decoded']).read_text());refs={n['$id']:n for n in walk(d['odin']) if '$id'in n};f=d['fields'];asset=d['_source']['asset']
 data=convert(d['odin'],asset,refs)
 events[f['ID']]={'id':f['ID'],'sourceId':e['id'],'eventType':f['eventType'],'condition':f['playCondition'] if f['conditionalPlay'] else '', 'triggerCondition':f['playCondition'],'repeatable':bool(f['canPlayMultipleTimes']),'triggerCountdown':f['TriggerCountdown'],'triggerCancel':bool(f['TriggeredCanCancel']),'startingContexts':f['StartingContexts'],'doHaggle':bool(f['DoHaggle']),'playerCanDecline':bool(f['PlayerCanDeclineDeal']),'item':ptr(f['Item'],asset),'itemFromContext':f['ContextWithItemID'] if f['ItemFromContext'] else None,'customer':ptr(f['Customer'],asset),'personality':f['CustomerAttribute']['Personality'],'defaultCards':[ptr(c,asset)['name'] for c in f['CustomerDefaultAssumptions'] if ptr(c,asset)],'intro':data.get('Intro2') or [],'outro':data.get('Outtro2') or [],'chunks':{c['ID']:c['eventData'] for c in (data.get('CallableChunks') or [])},'acceptableItems':[ptr(i,asset)['name'] for i in f['acceptableItems'] if ptr(i,asset)],'requiredCards':[ptr(i,asset)['name'] for i in f['requiredCards'] if ptr(i,asset)],'cardMode':f['CurationCardMode'],'skipCurationHaggle':bool(f['SkipCurationHaggle']),'skippedCurationNoBuy':bool(f['SkippedCurationHaggleNoBuy'])}
levels={}
for l in cat['levels']:
 def seq(k):return [x['event']['name'] if x['event'] else '@purchase' for x in l[k]]
 levels[l['name']]={'id':l['id'],'before':seq('BeforeStoreEvents'),'schedule':seq('Schedule'),'after':seq('AfterStoreEvents'),'startingContexts':l['dayStartingContexts'],'itemDifficulty':l['randomItemDifficulty'],'customerDifficulty':l['randomCustomerDifficulty']}
items=[]
for i in idx.values():
 if i.get('class')=='Item' and i.get('json'):
  f=json.loads((B/i['json']).read_text())['data']
  items.append({'id':i['name'],'random':not bool(f.get('CannotAppearAsRandomItem')) and not bool(f.get('Deprecated')),'randomItemLine':f.get('RandomItemLine'),'line':convert(f.get('GeneratedEventItemLine'),i['asset'],{}),'source':i['id']})
result={'version':'1.0.5 Demo','levels':levels,'events':events,'items':items,'limitations':['Only original Level day01, day02, day03 and triggeredEvents exist in this supplied Demo.','Challenge uses the supplied Demo random-item pool; missing day15–29 Level difficulty data is not invented.']}
s=json.dumps(result,ensure_ascii=False,separators=(',',':'))
(R/'src/native-campaign-data.ts').write_text('/** Generated by scripts/research/build_runtime_campaign.py. Original data, not implementation. */\nimport type {CampaignCatalog} from "./native-scheduler";\nexport const NATIVE_CAMPAIGN:CampaignCatalog=JSON.parse('+json.dumps(s,ensure_ascii=False)+');\n')
print({'events':len(events),'levels':len(levels),'items':len(items),'bytes':len(s.encode())})
